version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive
    - gosec
    - bodyclose
    - misspell
  settings:
    revive:
      rules:
        - name: var-naming
        - name: package-comments
        - name: exported

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
